export const SET_PEDIDOS = "SET_PEDIDOS"
export const GET_USER    = 'GET_USER'
export const LOGIN_USER    = 'LOGIN_USER'
export const LOGIN_USER_INFO    = 'LOGIN_USER_INFO'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_PEDIDOS_MESA = 'SET_PEDIDOS_MESA'
export const SET_TOTALVALOR = 'SET_TOTALVALOR'
export const SET_CARDAPIO   = 'SET_CARDAPIO'
export const SET_ADICIONAR_PEDIDO_ITENS = 'SET_ADICIONAR_PEDIDO_ITENS'
export const SET_ADICIONAR_PEDIDO = 'SET_ADICIONAR_PEDIDO'
export const SET_MESAS="SET_MESAS"
export const SET_ADICIONAR_PEDIDO_MESA = 'SET_ADICIONAR_PEDIDO_MESA'
export const SET_MODAL_COMMENTS = 'SET_MODAL_COMMENTS'
export const SET_ONOROF = 'SET_ONOROF'
export const SET_COMMENTS = 'SET_COMMENTS'
export const SET_QR_CODE = 'SET_QR_CODE'
export const RESET_STATE = 'RESET_STATE';

//
